import { useState, type RefObject } from "react";
import { validateExecutedStepInput } from "./planner-api-types";

interface PlannerJourneyActionProps { readonly step: { readonly sequenceLabel: string; readonly scheduledDate: string; readonly amountLabel: string }; readonly isPending: boolean; readonly onComplete: (amount: number, rate: number) => void; readonly onSkip: () => void; readonly onDetail: () => void; readonly onBack: () => void; readonly detailButtonRef: RefObject<HTMLButtonElement>; }
export function PlannerJourneyAction({ step, isPending, onComplete, onSkip, onDetail, onBack, detailButtonRef }: PlannerJourneyActionProps) {
  const [amount, setAmount] = useState(""); const [rate, setRate] = useState(""); const [error, setError] = useState("");
  const handleSubmit = (event: React.FormEvent) => { event.preventDefault(); const validation = validateExecutedStepInput({ executedAmount: Number(amount), executedRate: Number(rate) }); if (!validation.isValid) { setError(validation.message); return; } setError(""); onComplete(validation.value.executedAmount, validation.value.executedRate); };
  return <section className="planner-api-journey__scene" aria-labelledby="planner-api-action-question"><p className="planner-api-journey__eyebrow">4 / 5 다음 행동</p><h2 id="planner-api-action-question">{step.sequenceLabel}를 기록할까요?</h2><p className="planner-api-journey__lead">{step.scheduledDate} · {step.amountLabel}</p>
    <form className="planner-api-action" onSubmit={handleSubmit} noValidate><label>실행 외화 금액<input aria-invalid={Boolean(error)} disabled={isPending} inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label>실행 환율<input aria-invalid={Boolean(error)} disabled={isPending} inputMode="decimal" value={rate} onChange={(event) => setRate(event.target.value)} /></label>{error && <p className="planner-api-action__error" role="alert">{error}</p>}<button className="planner-api-journey__primary" type="submit" disabled={isPending}>{isPending ? "서버에 반영 중…" : "이번 회차 기록"}</button><button className="planner-api-journey__secondary" type="button" disabled={isPending} onClick={onSkip}>이번 회차 건너뛰기 미리보기</button></form>
    <div className="planner-api-journey__buttons"><button type="button" className="planner-api-journey__secondary" onClick={onBack}>Curve로 돌아가기</button><button ref={detailButtonRef} type="button" className="planner-api-journey__text-button" onClick={onDetail}>전체 계획 상세 보기</button></div></section>;
}
